name: flutter_starter_pro
description: A clean and customizable Flutter starter template that provides best practices, organized structure,
  localization support, state management (Cubit), and reusable UI components.
version: 1.0.8
repository: https://github.com/Luciferaloush/flutter_starter_pro

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
   archive: ^4.0.7
   path: ^1.8.0


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

executables:
  flutter_starter_pro: flutter_starter_pro